---
api_instance_uri: https://api-server/api/v1/instance
tls:
    ca: /etc/ssl/certs/ssl-cert-snakeoil.pem
cli:
    msyql:
        client: mycli
        args: "mycli -h dbod-%s -P %s"
    pg: 
        client: pgcli
        args: "pgcli -h dbod-%s -p %s -U postgres postgres"
